name=MQTT_Manager
version=2.1.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=A robust, non-blocking MQTT wrapper for ESP32/ESP8266.
paragraph=Simplifies MQTT connections using PubSubClient. Features include non-blocking auto-reconnects (WiFi & MQTT), Last Will and Testament (LWT) support, and automatic resubscription handling upon reconnection.
category=Communication
url=https://github.com/0ADILL3/MQTT_Manager
architectures=esp32, esp8266
depends=PubSubClient
includes=MQTT_Manager.h