name=MQTT_Manager
version=1.1.1
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Library pengelola koneksi MQTT dan OTA untuk ESP32.
paragraph=Library ini merupakan wrapper Object-Oriented untuk PubSubClient. Library ini menyediakan fitur koneksi ulang (auto-reconnect) WiFi dan MQTT secara otomatis, penyederhanaan fungsi publish/subscribe, serta integrasi mulus dengan Over-The-Air (OTA) via MQTT.
category=Communication
url=https://github.com/0ADILL3/MQTT_Manager
architectures=esp32, esp8266
depends=PubSubClient
includes=MQTT_Manager.h